export const GameRoomState = Object.freeze({
    WAITING_FOR_HOST: 'WAITING_FOR_HOST',
    CHOOSING_THEME: 'CHOOSING_THEME',
    GENERATING_SECRET_WORDS: 'GENERATING_SECRET_WORDS',
    CHOOSING_WORD: 'CHOOSING_WORD',
    DRAWING: 'DRAWING',
    ENDING: 'ENDING'
});